### ISSUE TITLE
Black bars on startup

### ISSUE THREAD

**Issue by ButterscotchV** [qwertysam/afroman-client#11]
When the game is started at default size, it renders with black bars

Image displaying this issue: [http://i.imgur.com/NgmTBTN.png](url)

**Comment by CardboardBread** [comment]
have you tried resizing the window?
i dont think afroman renders in windows's default window size, so it has to scale down to fit, if you fiddle with the window size, you can see this in action

**Comment by ButterscotchV** [comment]
That's the smallest size that it's limited to, so that's the size that it starts with
