### ISSUE TITLE
Closing game while in-game causes all kinds of errors

### ISSUE THREAD

**Issue by defaultsamson** [qwertysam/afroman-client#20]

**Comment by CardboardBread** [comment]
add a window listener to call the shutdown method (if it exists)

source: [http://stackoverflow.com/questions/16372241/run-function-on-jframe-close](http://stackoverflow.com/questions/16372241/run-function-on-jframe-close)

**Comment by CardboardBread** [comment]
or utilize the disconnect function on close (idk if that is a thing yet)

**Comment by defaultsamson** [comment]
The issue was that to properly disconnect without any errors, the client had to send the server a disconnect packet. If the game is closed through task manager then it spits errors (as well as sometimes when hitting the X to close the window). The server now detects players with terminated connections and deals with them before they cause any problems.
