### ISSUE TITLE
A server cannot start if a member closes the game by force

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#3]
If person A hosts a server, and person B joins it, then closes Afroman while in the lobby - without using the disconnect button - the game errors out and the host cannot start or close the server, possibly due to lobby members never responding to packets

the best solution i can think of is keep-alive packets, ones that contain very little data, but just enough that the server can say "this guy sent a keepalive packet, and he's already on the lobby list, so ill keep him in, if he doesn't send any for awhile, then i feckin burst him"

**Comment by CardboardBread** [comment]
if a users-in-lobby is unavailable, then keepalive can be used to validate users in the lobby, but can cause problems if some random goon sends keepalive packets

**Comment by CardboardBread** [comment]
Error is as follows:
Exception in thread "Client/Server/Game" java.lang.NullPointerException
    at ca.afroman.server.ServerGame.parsePacket(ServerGame.java:257)
    at ca.afroman.game.Game.tick(Game.java:165)
    at ca.afroman.server.ServerGame.tick(ServerGame.java:791)
    at ca.afroman.thread.DynamicTickRenderThread.onRun(DynamicTickRenderThread.java:45)
    at ca.afroman.thread.DynamicThread.run(DynamicThread.java:106)

**Comment by CardboardBread** [comment]
unfortunately, the buttons do not seem to give errors when pressed

**Comment by CardboardBread** [comment]
also you cant rejoin if the server is bugged by someone else

**Comment by defaultsamson** [comment]
As of the latest commit https://github.com/qwertysam/afroman-client/commit/ee670e7fa42e0437a24f33cbfb6cf114237793f5, closing the game using the X button will properly disconnect the player from the game. This issue will still persist if the game's process is forcefully killed.

**Comment by CardboardBread** [comment]
keepalive may be useful in the case of the program hanging or the process becoming unresponsive, although keepalive should be left to a later date

**Comment by defaultsamson** [comment]
I'll make a project for it to close this issue
