### ISSUE TITLE
Audio reset?

### ISSUE THREAD

**Issue by CardboardBread** [qwertysam/afroman-client#9]
when the close button is pressed, the menu music will replay itself, as it starts to close (takes about 0.5 seconds)

**Comment by CardboardBread** [comment]
giving the program time to settle(?) can relieve the issue, and it therefore shouldn't commonly by found in regular use
only with opening, and subsequently closing the program

**Comment by defaultsamson** [comment]
Added a new project for unifying shutdown behaviour across threads and operations.
